version: '3'
services:
  node-app:
    build: .
    image: node-app
    container_name: node_app
    command: npm start
    # env_file: .env
    environment:
      - DB_HOST=mysql
      - REDIS_HOST=redis
    ports:
      - '3000:3000'
    volumes:
      - .:/var/www
    networks:
      - node-network
  mysql:
    image: mysql:8.0
    container_name: mysql
    hostname: mysql
    environment:
      - MYSQL_DATABASE=u-home
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - '~/docker/db/data:/var/lib/mysql'
      - '~/docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - '~/docker/db/sql:/docker-entrypoint-initdb.d'
    networks:
      - node-network
  redis:
    image: redis:alpine
    container_name: redis
    privileged: true
    ports:
      - 6379:6379
    networks:
      - node-network

networks:
  node-network:
    driver: bridge