version: '3'
services:
  app:
    build: .
    image: node-app
    container_name: node-app
    # env_file: .env
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - REDIS_HOST=redis
    ports:
      - '3000:3000'
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/var/www
    networks:
      - node-network
  mysql:
    image: mysql:8.0
    container_name: mysql
    hostname: mysql
    environment:
      - MYSQL_DATABASE=u-home
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - '~/.docker/data/mysql:/var/lib/mysql'
    networks:
      - node-network
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - node-network
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
    volumes:
      - '~/.docker/minio/data:/export'
      - '~/.docker/minio/config:/root/.minio'
    environment:
      - MINIO_ACCESS_KEY=u-home-key
      - MINIO_SECRET_KEY=u-home-secret
    networks:
      - node-network
volumes:
  dbdata:
  node_modules:

networks:
  node-network:
    driver: bridge