export const command = Object.freeze({
  REQUEST_UPDATE_PROGRESS: 'REQUEST_UPDATE_PROGRESS',
  REQUEST_CANCEL: 'REQUEST_CANCEL',
  REQUEST_SEND_MEDIA: 'REQUEST_SEND_MEDIA',
  REQUEST_ESTIMATION_TIME: 'REQUEST_ESTIMATION_TIME',
  SUBMIT_ESTIMATION_TIME: 'SUBMIT_ESTIMATION_TIME',
  APPROVAL_ESTIMATION_TIME: 'APPROVAL_ESTIMATION_TIME',
  REQUEST_ESTIMATION_COST: 'REQUEST_ESTIMATION_COST',
  SUBMIT_ESTIMATION_COST: 'SUBMIT_ESTIMATION_COST',
  APPROVAL_ESTIMATION_COST: 'APPROVAL_ESTIMATION_COST',
  INFORM_MATERIAL_COST: 'INFORM_MATERIAL_COST',
  APPROVAL_MATERIAL_COST: 'APPROVAL_MATERIAL_COST',
  REQUEST_ACCEPTANCE: 'REQUEST_ACCEPTANCE',
  CONTINUE_CHATTING: 'CONTINUE_CHATTING',
  UPDATED_PROGRESS: 'UPDATED_PROGRESS',
});

export const commandMessage = Object.freeze({
  REQUEST_UPDATE_PROGRESS: 'chat.update_progress',
  REQUEST_CANCEL: 'chat.cancel',
  REQUEST_SEND_MEDIA: 'chat.send_media',
  REQUEST_ESTIMATION_TIME: 'chat.estimate_time',
  SUBMIT_ESTIMATION_TIME: 'chat.submit_estimate_time',
  APPROVAL_ESTIMATION_TIME: 'chat.approval_estimate_time',
  REQUEST_ESTIMATION_COST: 'chat.estimate_cost',
  SUBMIT_ESTIMATION_COST: 'chat.submit_estimate_cost',
  APPROVAL_ESTIMATION_COST: 'chat.approval_estimate_cost',
  INFORM_MATERIAL_COST: 'chat.inform_material_cost',
  APPROVAL_MATERIAL_COST: 'chat.approval_material_cost',
  REQUEST_ACCEPTANCE: 'chat.request_acceptance',
  CONTINUE_CHATTING: 'chat.continue_chatting',
  UPDATED_PROGRESS: 'chat.updated_progress',
});

export const commandRequests = [
  command.REQUEST_ACCEPTANCE,
  command.REQUEST_UPDATE_PROGRESS,
  command.REQUEST_ESTIMATION_TIME,
  command.REQUEST_CANCEL,
  command.REQUEST_SEND_MEDIA,
  command.REQUEST_ESTIMATION_COST,
  command.CONTINUE_CHATTING,
];
