export const issueStatus = Object.freeze({
  SYSTEM_VERIFYING: 'SYSTEM_VERIFYING',
  OPEN: 'OPEN',
  CHATTING: 'CHATTING',
  IN_PROGRESS: 'IN_PROGRESS',
  WAITING_VERIFY: 'WAITING_VERIFY',
  DONE: 'DONE',
  CANCELLED: 'CANCELLED',
});
